//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> QTY { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
